name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint and Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        java: [8.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run test

      - name: Test CLI HTML
        run: npm run cli-html

      - name: Test CLI Lint
        run: npm run cli-lint

      - name: Test NodeJS Api
        run: npm run nodejs-api
